defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/A/A.com.crt"
      keyFile = "/ssl/A/A.com.key"
      [[entryPoints.https.tls.certificates]]
      certFile = "/ssl/B/B.com.crt"
      keyFile = "/ssl/B/B.com.key"
