---
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "0.0.0.0"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: "v1.14.3"
controlPlaneEndpoint: "172.16.0.69:6443"
networking:
  serviceSubnet: "10.100.0.0/16"
  podSubnet: "10.200.0.0/16"
imageRepository: registry.aliyuncs.com/google_containers
etcd:
    external:
        endpoints:
        - https://172.16.0.69:2379
        - https://172.16.0.70:2379
        - https://172.16.0.71:2379
        caFile: /k8s/etcd/ssl/ca.pem
        certFile: /k8s/etcd/ssl/server.pem
        keyFile: /k8s/etcd/ssl/server-key.pem
